name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_matrix:
    name: Build Package Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.package_matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Create Package Matrix
        id: package_matrix
        run: uv run pymono matrix_strategy inputs

  test_package:
    runs-on: ubuntu-latest
    needs: build_matrix
    strategy:
      matrix: ${{ fromJson(needs.build_matrix.outputs.matrix) }}
    permissions:
      # Gives the action the necessary permissions for publishing new
      # comments in pull requests.
      pull-requests: write
      # Gives the action the necessary permissions for pushing data to the
      # python-coverage-comment-action branch, and for editing existing
      # comments (to avoid publishing multiple comments in the same PR)
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print Inputs
        run: |
          echo "Path: ${{ matrix.inputs.path }}"
          echo "Name: ${{ matrix.inputs.name }}"
          echo "Shared: ${{ matrix.inputs.shared }}"
      - name: "Check if ${{ matrix.inputs.name }} has changed"
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            is_changed:
              - '${{ matrix.inputs.path }}/**'
            is_shared_changed:
              - 'packages/shared/**'
      - name: Run tests
        if: ${{ steps.changes.outputs.is_changed == 'true' || steps.changes.outputs.is_shared_changed == 'true' }}
        uses: ./.github/actions/uvtest
        with:
          name: ${{ matrix.inputs.name }}
          path: ${{ matrix.inputs.path }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Install uv
      #   if: ${{ steps.changes.outputs.is_changed == 'true' || steps.changes.outputs.is_shared_changed == 'true' }}
      #   uses: astral-sh/setup-uv@v4
      # - name: Sync
      #   if: ${{ steps.changes.outputs.is_changed == 'true' || steps.changes.outputs.is_shared_changed == 'true' }}
      #   run: uv sync --directory ${{ matrix.inputs.path }} --all-extras --dev
      # - name: Test
      #   if: ${{ steps.changes.outputs.is_changed == 'true' || steps.changes.outputs.is_shared_changed == 'true' }}
      #   run: uv run --directory ${{ matrix.inputs.path }} pytest tests
      # - name: Coverage comment
      #   if: ${{ steps.changes.outputs.is_changed == 'true' || steps.changes.outputs.is_shared_changed == 'true' }}
      #   uses: MishaKav/pytest-coverage-comment@main
      #   with:
      #     github-token: ${{ github.token }}
      #     unique-id-for-comment: ${{ matrix.inputs.name }}
      #     title: "Coverage report for '${{ matrix.inputs.name }}'"
      #     pytest-xml-coverage-path: "${{ matrix.inputs.path }}/coverage.xml"
      # - name: Sync Shared
      #   # TODO : This is a temporary solution, we need to find a better way to handle shared packages
      #   if: ${{ steps.changes.outputs.is_changed == 'true' || steps.changes.outputs.is_shared_changed == 'true' }}
      #   run: uv sync --all-extras --dev
      # - name: Test Shared
      #   # TODO : This is a temporary solution, we need to find a better way to handle shared packages
      #   if: ${{ steps.changes.outputs.is_changed == 'true' || steps.changes.outputs.is_shared_changed == 'true' }}
      #   run: uv run pytest tests
      # - name: Coverage comment
      #   if: ${{ steps.changes.outputs.is_changed == 'true' || steps.changes.outputs.is_shared_changed == 'true' }}
      #   uses: MishaKav/pytest-coverage-comment@main
      #   with:
      #     github-token: ${{ github.token }}
      #     unique-id-for-comment: "shared"
      #     title: "Coverage report for 'shared'"
      #     pytest-xml-coverage-path: "coverage.xml"
